version: '3'
services:   
    eureka:
        build:
            context: ./eureka
        container_name: eureka
        ports:
            - "8761:8761"
        restart: always
        networks:
            - eretail-net         
      
    gateway:
        depends_on:
            - eureka
        build:
            context: ./gateway
        container_name: gateway
        ports:
            - "8765:8765"
        restart: always
        environment:
            - URL_EUREKA=http://eureka:8761/eureka
        networks:
            - eretail-net     
            
    sale-service:
        depends_on:
            - gateway
            - eureka
        build:
            context: ./sale-service
        container_name: sale-service
        restart: always
        environment:
            - URL_EUREKA=http://eureka:8761/eureka
            - URL_PRODUCT=http://products-service
        networks:
            - eretail-net
            
    products-service:
        build:
            context: ./products-service
        container_name: products-service
        ports:
           - "5000:5000"
        restart: always
        environment:
            - FLASK_ENV=app.py
        networks:
            - eretail-net
            
networks:
  eretail-net:
    driver: bridge 